func risky() {
    throw("danger zone")
}

try {
    risky()
} except err {
    print("Caught error:", err)
}
